export type GlossaryEntry = { title: string; body: string };

export const glossary: Record<string, GlossaryEntry> = {
  "nav": { title: "Net Asset Value (NAV)", body: "The total market value of everything the fund owns, minus what it owes. It's the fund's bottom-line worth at any moment." },
  "p&l": { title: "Profit & Loss (P&L)", body: "How much money the fund has made or lost over a period. A daily P&L tells you whether today was up or down." },
  "pnl": { title: "Profit & Loss (P&L)", body: "How much money the fund has made or lost over a period." },
  "alpha": { title: "Alpha", body: "Returns above what the broader market would give you for free. Generating alpha is the entire point of a hedge fund." },
  "sharpe": { title: "Sharpe Ratio", body: "Return per unit of risk. Higher is better. Above 1 is decent, above 2 is excellent, above 3 is exceptional." },
  "sortino": { title: "Sortino Ratio", body: "Like Sharpe, but only penalizes downside volatility. Useful when upside swings shouldn't count against you." },
  "drawdown": { title: "Drawdown", body: "The peak-to-trough drop in the fund's value. \"Max drawdown\" is the worst such drop on record." },
  "var": { title: "Value at Risk (VaR)", body: "A statistical estimate of the worst loss you'd expect on a normal bad day. \"VaR(99,1d) = 1.8%\" means: on the worst 1% of days, expect to lose at least 1.8%." },
  "beta": { title: "Beta", body: "How much a position moves when the overall market moves. Beta of 1 = moves with the market; 0 = market-neutral; 2 = twice as sensitive." },
  "factor exposure": { title: "Factor Exposure", body: "How much of your portfolio's behavior is driven by underlying themes — momentum, value, quality, interest-rate sensitivity, etc." },
  "factor": { title: "Factor", body: "A persistent driver of returns across many securities — e.g. momentum, value, size, quality." },
  "leverage": { title: "Leverage", body: "Borrowing to amplify positions. \"Net leverage 2.1×\" means the fund controls $2.10 of exposure for every $1 of its own capital." },
  "10-k": { title: "10-K", body: "A public company's annual filing with the SEC. Hundreds of pages covering business, risks, and financials in detail." },
  "8-k": { title: "8-K", body: "An SEC filing companies must submit when something material happens between annual reports — exec changes, deals, etc." },
  "13f": { title: "13F", body: "A quarterly disclosure of holdings that big institutional investors must file. Lets you see what major funds own." },
  "s-1": { title: "S-1", body: "The filing a private company submits to the SEC when it wants to go public." },
  "earnings call": { title: "Earnings Call", body: "A scheduled call where a company's executives walk through quarterly results and take analyst questions." },
  "vol": { title: "Volatility", body: "How much a price swings around. High vol = wild moves; low vol = calm. Measured in % per day or year." },
  "volatility": { title: "Volatility", body: "How much a price swings around. High vol = wild moves; low vol = calm." },
  "vix": { title: "VIX", body: "An index of expected near-term S&P 500 volatility, derived from option prices. Often called the \"fear gauge.\"" },
  "move": { title: "MOVE Index", body: "The bond-market version of the VIX — expected volatility in US Treasury yields." },
  "bp": { title: "Basis Point (bp)", body: "1/100th of a percent. 50 basis points = 0.50%. Used because finance argues over fractions of a percent." },
  "basis point": { title: "Basis Point", body: "1/100th of a percent. 50bp = 0.50%." },
  "slippage": { title: "Slippage", body: "The difference between the price you wanted and the price you actually got when executing a trade." },
  "iceberg": { title: "Iceberg Order", body: "An order broken into small visible pieces, with most of the size hidden, so the market doesn't see how much you're trying to trade." },
  "hedge": { title: "Hedge", body: "A second position taken specifically to offset risk in the first — like insurance." },
  "long": { title: "Long", body: "Owning something, betting it goes up." },
  "short": { title: "Short", body: "Borrowing and selling something, betting it goes down so you can buy it back cheaper." },
  "pair trade": { title: "Pair Trade", body: "Long one security and short a related one, isolating the gap between them. Removes market direction from the bet." },
  "skew": { title: "Skew", body: "An asymmetry in option prices — typically, puts (downside) cost more than calls (upside). Tells you what the market is afraid of." },
  "term structure": { title: "Term Structure", body: "How a quantity (rates, vol, futures prices) varies across maturities — 1 month vs. 3 months vs. 1 year, etc." },
  "convex": { title: "Convex", body: "A position whose payoff curves favorably — gains accelerate as things move your way, losses decelerate against you." },
  "backtest": { title: "Backtest", body: "Simulating a strategy against historical data to see how it would have performed." },
  "alt-data": { title: "Alternative Data", body: "Non-traditional signals — satellite imagery, credit-card flows, app downloads, web scrapes — used to predict company performance." },
  "alt data": { title: "Alternative Data", body: "Non-traditional signals — satellite imagery, credit-card flows, web scrapes — used to predict performance." },
  "thesis": { title: "Investment Thesis", body: "The argument for why a position should make money. Good ones are specific, falsifiable, and time-bounded." },
  "conviction": { title: "Conviction", body: "How strongly you believe in a thesis. Higher-conviction ideas usually get larger position sizes." },
  "capex": { title: "Capex", body: "Capital expenditure — money a company spends on long-lived assets (factories, equipment, chips)." },
  "dxy": { title: "DXY", body: "The US dollar index — value of the dollar against a basket of major foreign currencies." },
  "ust": { title: "US Treasuries", body: "Bonds issued by the US government. \"UST 10Y\" = the 10-year yield. The risk-free anchor of most pricing." },
  "fomc": { title: "FOMC", body: "The Federal Reserve committee that sets US interest rates. Its decisions move every major market." },
  "boj": { title: "BoJ", body: "Bank of Japan — Japan's central bank." },
  "ecb": { title: "ECB", body: "European Central Bank." },
  "monte carlo": { title: "Monte Carlo Simulation", body: "Running thousands of randomized future scenarios to estimate the distribution of possible outcomes." },
  "mc": { title: "Monte Carlo Simulation", body: "Randomized future scenarios to estimate the distribution of outcomes." },
  "quorum": { title: "Quorum", body: "The minimum agreement threshold needed for a decision to pass. Here: across agents voting on a trade." },
  "ingest": { title: "Ingestion", body: "The process of pulling documents, filings, or data into the system to be parsed and stored." },
  "inference": { title: "Inference", body: "Running an AI model to produce output (an answer, a score, a forecast). Counted in tokens or requests per second." },
  "vector store": { title: "Vector Store", body: "A database that indexes documents by their AI-generated \"embeddings\" so the system can search by meaning, not keywords." },
  "embedding": { title: "Embedding", body: "A numerical fingerprint of a piece of text. Similar meanings = similar fingerprints." },
  "retrieval": { title: "Retrieval", body: "Fetching the right documents from memory to give an AI model relevant context before it answers." },
  "agent": { title: "AI Agent", body: "A self-directed program that uses an LLM to take actions in the world — read a filing, score a thesis, place a trade." },
  "swarm": { title: "Agent Swarm", body: "Many AI agents operating in parallel, often coordinating or debating, to attack a problem from different angles." },
  "orchestrator": { title: "Orchestrator", body: "The supervisor agent that routes work, allocates compute, and resolves conflicts between specialist agents." },
  "dissent": { title: "Dissent", body: "When an agent disagrees with the swarm's emerging consensus. Surfaced to humans for review." },
  "execution": { title: "Execution", body: "Actually placing the trades — choosing venues, sizing slices, and timing them to minimize market impact." },
  "venue": { title: "Venue", body: "An exchange or trading destination where orders get matched — NYSE, NASDAQ, CME, etc." },
  "latency": { title: "Latency", body: "How long an action takes, measured in milliseconds. Lower is better; every ms matters in execution." },
  "p50": { title: "p50 (Median)", body: "The middle value — half of samples are faster, half slower. p95 / p99 are the worse tails." },
  "p99": { title: "p99", body: "The 99th-percentile worst-case — only 1% of events are slower than this. The tail that matters." },
  "rebalance": { title: "Rebalance", body: "Adjusting position sizes back toward target weights as prices and views change." },
  "stress test": { title: "Stress Test", body: "Simulating extreme but plausible bad scenarios (2008, COVID-2020, etc.) to see how the portfolio survives." },
  "liquidity": { title: "Liquidity", body: "How easily you can buy or sell something without moving the price. Cash = perfectly liquid; private equity = not." },
  "quiet period": { title: "Quiet Period", body: "A regulated window before earnings during which companies can't discuss financials publicly. Violations are a big deal." },
  "macro": { title: "Macro", body: "Top-down trading driven by economic forces — rates, growth, inflation, currencies — rather than individual companies." },
};

export function lookup(term: string): GlossaryEntry | undefined {
  return glossary[term.toLowerCase()];
}
